name: nezha美化文件

on:
  push:
    branches:
      - main

jobs:
  clone_download_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Clone NezhaThemeCustom
      run: git clone https://github.com/kshipeng/nezhaThemeCustom.git

    - name: 制作kshipengTheme.tar.gz
      run: |
        rm -rf nezhaThemeCustom theme resource1.tar.gz resource
        git clone https://github.com/kshipeng/nezhaThemeCustom.git
        mkdir -p resource/template/theme-custom
        cp -r nezhaThemeCustom/template/* resource/template/theme-custom/
        tar czf kshipengTheme.tar.gz resource

    - name: 制作amzayoTheme.tar.gz
      run: |
        rm -rf nezhaThemeCustom amzayo amzayo* resource
        wget https://cdn.amzayo.top/static/public/amzayo_template_fin_net.zip
        unzip amzayo_template_fin_net.zip -d amzayo_template
        mkdir -p resource/template/theme-custom
        mkdir -p resource/static/custom
        cp -r amzayo_template/template/* resource/template/theme-custom/
        cp -r amzayo_template/static/* resource/static/custom/
        tar czf amzayoTheme.tar.gz resource
      
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          kshipengTheme.tar.gz
          amzayoTheme.tar.gz
        tag_name: "nezhaTheme-page"
        token: ${{ secrets.YOUR_TOKEN }}
        body: |
          #哪吒美化文件打包
          kshipengTheme.tar.gz：`https://github.com/kshipeng/nezhaThemeCustom`
          amzayoTheme.tar.gz：`https://blog.amzayo.com/index.php/archives/28`
